language: cpp

git:
  depth: 1

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5 # support c++14
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
         - TARGET=lnx
    - os: osx
      osx_image: xcode8.3 # Tracvis default: OS X 10.12.6 and Xcode 8.3.3
      env: TARGET=mac

before_install:
  - eval "${MATRIX_EVAL}"
  - git submodule update --init --remote --depth=3

script:
  # - mkdir build && cd build && cmake -DBATCH_VERSION=ON -DUSE_OPENJPEG=ON -DUSE_JPEGLS=true -DZLIB_IMPLEMENTATION=Cloudflare .. && make && cd -
  - mkdir build && cd build && cmake -DBATCH_VERSION=OFF -DUSE_OPENJPEG=ON -DUSE_JPEGLS=true -DZLIB_IMPLEMENTATION=Cloudflare .. && make && cd -
  - export PATH=$PWD/build/bin:$PATH
  - cd dcm_qa && ./batch.sh && cd -
  - cd dcm_qa_nih && ./batch.sh && cd -
  - cd dcm_qa_uih && ./batch.sh && cd -

before_deploy:
  - zip -j dcm2niix_${TARGET}.zip build/bin/*
  - sleep 300 # make sure appveyor deployment is done, thus proper release name is set

deploy:
  provider: releases
  api_key:
    secure: sVIYRakcEQdMPEdGSSePtMVCMQvaohqV7NNzEErAgZ+b/4ofv2aPpJb5kNTv3JRl2FrPy7iXJ8lOUQ/95pqvimX6jv5ztksTNXtSMnHZNbjjWwIc99enPY+mSdWMO2lb9vGBWQ9GNfXjmk7MgtDHPjjygbuZfUw9fmGy4ocxkws=
  file_glob: true
  file: dcm2niix*.zip
  skip_cleanup: true
  on:
    tags: true
