version: build-{build}

image: Visual Studio 2015

configuration: Release

platform: x64

clone_depth: 1

clone_folder: c:\projects\dcm2niix

init:
- ps: >-
    $env:DATE = $(Get-Date -Format d-MMM-yyyy)

    $githash = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)

    $gittag = if ($env:APPVEYOR_REPO_TAG -eq $True) {"_$($env:APPVEYOR_REPO_TAG_NAME)"} else {""}

    Update-AppveyorBuild -Version "$($env:DATE)_g${githash}${gittag}"

    $env:release_version = $(Get-Date -Format d-MMMM-yyyy)

before_build:
- cmd: >-
    echo "Running cmake"

    mkdir c:\projects\dcm2niix\build

    cd c:\projects\dcm2niix\build

    cmake -Wno-dev -G "Visual Studio 14 2015 Win64" -DBATCH_VERSION=ON -DUSE_OPENJPEG=ON -DUSE_JPEGLS=true ..\

build:
  project: c:\projects\dcm2niix\build\dcm2niix.sln

  verbosity: normal

after_build:
- ps: >-
    cd c:\projects\dcm2niix

    7z a dcm2niix_win.zip c:\projects\dcm2niix\build\bin\* >$null

artifacts:
  - path: dcm2niix*.zip
    name: dcm2niix

deploy:
  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: version $(release_version) ($(appveyor_repo_tag_name))
    description: ""
    auth_token:
      secure: gCltVLQEWsjSTRlsi8qw7FGP54ujBq60apjXkWTV954b65bOHl95hXMxxkQ734L4
    artifact: dcm2niix
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
